take_medicine:
  name: Take Medicine
  description: Marks the medicine as taken.
  target:
    entity:
      integration: medicine_tracker
      domain: sensor
  fields:
    time_taken:
      name: Time Taken
      description: Optional override for when it was taken. Defaults to now.
      selector:
        datetime:

reset_history:
  name: Reset History
  description: Clears the taken history and resets the last taken date.
  target:
    entity:
      integration: medicine_tracker
      domain: sensor